### ISSUE TITLE
Submission Review Notes

### ISSUE THREAD

**Issue by dmosorast** [DeputyApp/singer-tap-deputy#7]
Adding notes to this issue as I review this tap for acceptance. These should be rather small but important changes to make before we can move this tap forward.

**Metadata**
It looks like [the custom metadata for `resource`](https://github.com/DeputyApp/singer-tap-deputy/blob/master/tap_deputy/discover.py#L83) is written has the wrong namespace. It should be `tap-deputy.resource`.

**Del on kwargs**
Should [this line](https://github.com/DeputyApp/singer-tap-deputy/blob/master/tap_deputy/client.py#L71) be calling delete on a parameter passed in? I'm not quite sure how Python behaves in all `kwargs` situations (e.g., splat, named keywords, etc.), but this seems like a side-effect that would be better avoided.

**all_selected**
This should be removed from [here](https://github.com/DeputyApp/singer-tap-deputy/blob/master/tap_deputy/sync.py#L89-L91). I see the usefulness of this feature to enable testing without having to select all streams, however it should be an optional configuration argument, rather than implied by the absence of a catalog. The absence of a catalog should mean *no streams* are selected, since that's what it is.

**current_stream**
This isn't being handled correctly ([here](https://github.com/DeputyApp/singer-tap-deputy/blob/master/tap_deputy/sync.py#L97)), it should attempt to run through every stream when it finds a `current_stream` state entry, rather than skipping earlier streams and only attempting them on the next tap run.  We just created a helper function to manage this called `get_selected_streams` on the `Catalog` class in singer-python 5.7 ([implementation](https://github.com/singer-io/singer-python/pull/100/files#diff-315e9805b91c0c7969fb8fb4680a49e2R143))

**Comment by awm33** [comment]
@dmosorast

> Metadata
It looks like the custom metadata for resource is written has the wrong namespace. It should be tap-deputy.resource.

Done.

> Del on kwargs
Should this line be calling delete on a parameter passed in? I'm not quite sure how Python behaves in all kwargs situations (e.g., splat, named keywords, etc.), but this seems like a side-effect that would be better avoided.

kwargs are a dictionary and can be manipulated like one. Here, the scope would be isolated to a function.

> all_selected
This should be removed from here. I see the usefulness of this feature to enable testing without having to select all streams, however it should be an optional configuration argument, rather than implied by the absence of a catalog. The absence of a catalog should mean no streams are selected, since that's what it is.

The intention of that is to handle the case when the tap is run without a catalog. I actually don't usually handle this case, but saw it on another new tap I didn't author and thought it was a good idea since the `--catalog` is an option. I can remove the default if desired and the tap would hard fail without a catalog.

> current_stream
This isn't being handled correctly (here), it should attempt to run through every stream when it finds a current_stream state entry, rather than skipping earlier streams and only attempting them on the next tap run. We just created a helper function to manage this called get_selected_streams on the Catalog class in singer-python 5.7 (implementation)

Taps are supposed to pick up where they left off using state to store the currently syncing stream. Are you proposing to remove this functionality?

**Comment by dmosorast** [comment]
Re: Lack of a `--catalog` parameter.

I'm not sure where my head was at when I wrote that, but looking through the Spec and how we handle the case where a catalog isn't provided, it seems like this should be okay.

Re: `current_stream` handling

You're correct that a tap should resume from the stream in the state, but it should run through all the streams when it's invoked. The way I read this is that if there are streams `["A","B","C","D"]` and a state with `{"current_stream": "C"}`, the tap will only run `["C","D"]`, whereas it should run `["C","D","A","B"]` in that order.

**Comment by awm33** [comment]
@dmosorast That's not how other taps behave and I don't believe that to be desired behavior. Eg, a tap that runs once a day is running, it syncs "A", "B", and fails or is terminated on "C". It retries 10 minutes later, picking up at "C", then finishing with "D". "A" and "B" should be the next run.

**Comment by dmosorast** [comment]
That approach was an oversight, and we're updating taps to treat the streams as a kind of circular queue, where if a tap is run daily, fails day 1 and succeeds day 2, the user doesn't have to wait until day 3 or intervene manually to get the other streams' data.

[This is the official implementation](https://github.com/singer-io/singer-python/pull/100/files#diff-315e9805b91c0c7969fb8fb4680a49e2R127), on the Catalog class, but there are a few examples in the wild in [tap-hubspot](https://github.com/singer-io/tap-hubspot/blob/master/tap_hubspot/__init__.py#L792-L803) and [tap-shopify](https://github.com/singer-io/tap-shopify/blob/master/tap_shopify/__init__.py#L95-L106), for example.

**Comment by jacobrobertbaca** [comment]
Hey @awm33 I'm taking over for @dmosorast here, any questions/updates here?

**Comment by awm33** [comment]
Hi @jacobrobertbaca , I updated the tap to use the recently released `get_selected_streams` and `set_currently_syncing` functions, as Dan instructed above.

**Comment by dmosorast** [comment]
These fixes are complete! Closing.
